wintypes: 
{
	tooltip = { fade = true; shadow = true; opacity = 1.0; focus = true; }
	dock = { shadow = true; clip-shadow-above = false; }
	dnd = { shadow = false; }
	popup_menu = { opacity = false; shadow = true }
	dropdown_menu = { opacity = false; shadow = true }
};

shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Rofi'",
	"class_g = 'Discord'",
	"class_g = 'Firefox'",
	"_GTK_FRAME_EXTENDS@:c"
];

#Fading

fading = true;
fade-in-step = 0.02;
fade-out-step = 0.02;

#opacity

active-opacity = 1.0;
inactive-opacity = 1.0;

focus-exclude = [
	"class_g = 'Rofi'",
	"class_g = 'Kitty'",
	"class_g = 'Discord'",
	"class_g = 'nvim'",
	"class_g = 'Firefox'",
	"_GTK_FRAME_EXTENDS@:c"
];

opacity-rule = [
	"88:class_g = 'kitty' && !focused",
	"88:class_g = 'kitty' && focused",
];
